/*
	_bot_motor_data
	GENERATED by tools/gen_motor_model.py from human demo data. Do not edit.
	Human movement state machine per profile: dwell-time deciles (s),
	next-state weights (per mille) and time share (per mille);
	S&D context lifts per 512u map area and round phase (x100, see motorNext).
	  sd context: 135 areas (512u) on mp_backlot, mp_bog, mp_crossfire, mp_overgrown, 6 round phases
	  sd: sprint 20%, run 22%, ads_walk 9%, crouch_walk 10%, still_stand 23%, still_crouch 11%, prone 6% (565 player-min)
	  respawn: sprint 15%, run 11%, ads_walk 6%, crouch_walk 13%, still_stand 19%, still_crouch 30%, prone 6% (118 player-min)
*/

/*
	Returns the data string for key (profile_state_field), or undefined.
*/
motor_data( key )
{
	switch ( key )
	{
		case "sd_sprint_dwell": return "0.20,0.30,0.40,0.55,0.70,0.95,1.20,1.70,2.80";
		case "sd_sprint_next": return "run:621,crouch_walk:252,ads_walk:103,still_stand:20,still_crouch:4";
		case "sd_sprint_share": return "201";
		case "sd_run_dwell": return "0.15,0.20,0.30,0.35,0.50,0.65,0.85,1.15,1.70";
		case "sd_run_next": return "sprint:542,still_stand:223,ads_walk:117,crouch_walk:106,still_crouch:12";
		case "sd_run_share": return "216";
		case "sd_ads_walk_dwell": return "0.15,0.20,0.25,0.35,0.40,0.55,0.70,0.95,1.40";
		case "sd_ads_walk_next": return "still_stand:698,run:210,crouch_walk:54,sprint:25,still_crouch:13,prone:1";
		case "sd_ads_walk_share": return "88";
		case "sd_crouch_walk_dwell": return "0.20,0.25,0.30,0.35,0.45,0.55,0.70,0.90,1.40";
		case "sd_crouch_walk_next": return "still_crouch:417,run:247,sprint:135,prone:94,ads_walk:79,still_stand:28";
		case "sd_crouch_walk_share": return "96";
		case "sd_still_stand_dwell": return "0.15,0.20,0.30,0.40,0.50,0.65,0.85,1.25,2.25";
		case "sd_still_stand_next": return "run:517,ads_walk:364,still_crouch:65,crouch_walk:26,sprint:26,prone:1";
		case "sd_still_stand_share": return "226";
		case "sd_still_crouch_dwell": return "0.20,0.20,0.30,0.40,0.50,0.70,1.00,1.55,2.65";
		case "sd_still_crouch_next": return "crouch_walk:633,still_stand:178,run:96,ads_walk:42,prone:35,sprint:16";
		case "sd_still_crouch_share": return "113";
		case "sd_prone_dwell": return "0.45,0.75,0.90,1.20,1.65,2.05,2.65,4.50,7.35";
		case "sd_prone_next": return "crouch_walk:425,still_crouch:385,run:172,still_stand:17,ads_walk:2";
		case "sd_prone_share": return "60";
		case "sd_area_mp_backlot_-2_-2": return "sprint:82,run:72,ads_walk:96,crouch_walk:144,still_stand:36,still_crouch:281,prone:72";
		case "sd_area_mp_backlot_-2_-1": return "sprint:51,run:78,ads_walk:72,crouch_walk:144,still_stand:87,still_crouch:176,prone:236";
		case "sd_area_mp_backlot_-2_0": return "sprint:69,run:79,ads_walk:70,crouch_walk:142,still_stand:68,still_crouch:205,prone:175";
		case "sd_area_mp_backlot_-2_1": return "sprint:152,run:138,ads_walk:165,crouch_walk:103,still_stand:32,still_crouch:25,prone:86";
		case "sd_area_mp_backlot_-2_2": return "sprint:165,run:78,ads_walk:94,crouch_walk:147,still_stand:111,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_-1_-5": return "sprint:130,run:104,ads_walk:25,crouch_walk:25,still_stand:183,still_crouch:25,prone:123";
		case "sd_area_mp_backlot_-1_-4": return "sprint:106,run:134,ads_walk:47,crouch_walk:51,still_stand:135,still_crouch:73,prone:25";
		case "sd_area_mp_backlot_-1_-3": return "sprint:45,run:81,ads_walk:97,crouch_walk:98,still_stand:174,still_crouch:141,prone:25";
		case "sd_area_mp_backlot_-1_-2": return "sprint:77,run:58,ads_walk:128,crouch_walk:148,still_stand:110,still_crouch:91,prone:235";
		case "sd_area_mp_backlot_-1_-1": return "sprint:96,run:106,ads_walk:156,crouch_walk:146,still_stand:79,still_crouch:48,prone:111";
		case "sd_area_mp_backlot_-1_0": return "sprint:58,run:75,ads_walk:180,crouch_walk:105,still_stand:141,still_crouch:109,prone:66";
		case "sd_area_mp_backlot_-1_1": return "sprint:69,run:114,ads_walk:111,crouch_walk:79,still_stand:122,still_crouch:133,prone:25";
		case "sd_area_mp_backlot_-1_2": return "sprint:123,run:171,ads_walk:98,crouch_walk:31,still_stand:87,still_crouch:25,prone:72";
		case "sd_area_mp_backlot_-1_3": return "sprint:307,run:106,ads_walk:25,crouch_walk:25,still_stand:43,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_0_-5": return "sprint:261,run:96,ads_walk:114,crouch_walk:25,still_stand:41,still_crouch:54,prone:25";
		case "sd_area_mp_backlot_0_-4": return "sprint:212,run:105,ads_walk:58,crouch_walk:29,still_stand:88,still_crouch:45,prone:25";
		case "sd_area_mp_backlot_0_-3": return "sprint:150,run:112,ads_walk:64,crouch_walk:59,still_stand:93,still_crouch:65,prone:88";
		case "sd_area_mp_backlot_0_-2": return "sprint:80,run:115,ads_walk:109,crouch_walk:113,still_stand:122,still_crouch:71,prone:40";
		case "sd_area_mp_backlot_0_-1": return "sprint:66,run:70,ads_walk:69,crouch_walk:110,still_stand:155,still_crouch:165,prone:25";
		case "sd_area_mp_backlot_0_0": return "sprint:110,run:115,ads_walk:169,crouch_walk:116,still_stand:73,still_crouch:85,prone:25";
		case "sd_area_mp_backlot_0_1": return "sprint:63,run:118,ads_walk:119,crouch_walk:77,still_stand:136,still_crouch:91,prone:57";
		case "sd_area_mp_backlot_0_2": return "sprint:229,run:187,ads_walk:25,crouch_walk:25,still_stand:29,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_0_3": return "sprint:347,run:86,ads_walk:25,crouch_walk:41,still_stand:25,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_0_4": return "sprint:176,run:70,ads_walk:25,crouch_walk:25,still_stand:206,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_1_-4": return "sprint:124,run:156,ads_walk:78,crouch_walk:29,still_stand:115,still_crouch:38,prone:25";
		case "sd_area_mp_backlot_1_-3": return "sprint:75,run:150,ads_walk:58,crouch_walk:45,still_stand:109,still_crouch:140,prone:25";
		case "sd_area_mp_backlot_1_-2": return "sprint:108,run:78,ads_walk:33,crouch_walk:153,still_stand:82,still_crouch:156,prone:97";
		case "sd_area_mp_backlot_1_-1": return "sprint:54,run:77,ads_walk:151,crouch_walk:194,still_stand:67,still_crouch:75,prone:331";
		case "sd_area_mp_backlot_1_0": return "sprint:97,run:94,ads_walk:131,crouch_walk:142,still_stand:82,still_crouch:95,prone:90";
		case "sd_area_mp_backlot_1_1": return "sprint:46,run:75,ads_walk:57,crouch_walk:127,still_stand:84,still_crouch:167,prone:371";
		case "sd_area_mp_backlot_1_2": return "sprint:161,run:172,ads_walk:64,crouch_walk:44,still_stand:70,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_1_3": return "sprint:196,run:174,ads_walk:29,crouch_walk:25,still_stand:65,still_crouch:25,prone:25";
		case "sd_area_mp_backlot_2_-3": return "sprint:75,run:118,ads_walk:222,crouch_walk:75,still_stand:71,still_crouch:69,prone:197";
		case "sd_area_mp_backlot_2_-2": return "sprint:89,run:89,ads_walk:125,crouch_walk:159,still_stand:69,still_crouch:167,prone:25";
		case "sd_area_mp_backlot_2_-1": return "sprint:76,run:94,ads_walk:229,crouch_walk:110,still_stand:105,still_crouch:53,prone:105";
		case "sd_area_mp_backlot_2_0": return "sprint:81,run:79,ads_walk:174,crouch_walk:114,still_stand:129,still_crouch:93,prone:30";
		case "sd_area_mp_backlot_2_1": return "sprint:109,run:77,ads_walk:177,crouch_walk:201,still_stand:46,still_crouch:103,prone:59";
		case "sd_area_mp_backlot_2_2": return "sprint:84,run:123,ads_walk:206,crouch_walk:107,still_stand:92,still_crouch:58,prone:25";
		case "sd_area_mp_backlot_2_3": return "sprint:75,run:109,ads_walk:63,crouch_walk:95,still_stand:106,still_crouch:108,prone:188";
		case "sd_area_mp_backlot_3_-1": return "sprint:77,run:122,ads_walk:97,crouch_walk:194,still_stand:73,still_crouch:78,prone:44";
		case "sd_area_mp_backlot_3_0": return "sprint:43,run:43,ads_walk:211,crouch_walk:129,still_stand:131,still_crouch:190,prone:47";
		case "sd_area_mp_backlot_3_1": return "sprint:89,run:122,ads_walk:135,crouch_walk:123,still_stand:97,still_crouch:27,prone:117";
		case "sd_area_mp_backlot_3_2": return "sprint:88,run:67,ads_walk:147,crouch_walk:101,still_stand:88,still_crouch:65,prone:385";
		case "sd_area_mp_backlot_3_3": return "sprint:25,run:25,ads_walk:25,crouch_walk:41,still_stand:160,still_crouch:400,prone:89";
		case "sd_area_mp_backlot_4_-1": return "sprint:37,run:116,ads_walk:173,crouch_walk:114,still_stand:130,still_crouch:104,prone:25";
		case "sd_area_mp_backlot_4_1": return "sprint:62,run:101,ads_walk:142,crouch_walk:134,still_stand:115,still_crouch:119,prone:25";
		case "sd_area_mp_bog_4_0": return "sprint:209,run:26,ads_walk:25,crouch_walk:174,still_stand:63,still_crouch:155,prone:97";
		case "sd_area_mp_bog_4_1": return "sprint:366,run:91,ads_walk:55,crouch_walk:47,still_stand:35,still_crouch:25,prone:25";
		case "sd_area_mp_bog_4_2": return "sprint:255,run:194,ads_walk:47,crouch_walk:115,still_stand:25,still_crouch:25,prone:25";
		case "sd_area_mp_bog_4_3": return "sprint:117,run:124,ads_walk:32,crouch_walk:249,still_stand:25,still_crouch:25,prone:348";
		case "sd_area_mp_bog_5_-1": return "sprint:98,run:105,ads_walk:30,crouch_walk:25,still_stand:206,still_crouch:25,prone:31";
		case "sd_area_mp_bog_5_0": return "sprint:85,run:117,ads_walk:103,crouch_walk:97,still_stand:119,still_crouch:107,prone:26";
		case "sd_area_mp_bog_5_1": return "sprint:102,run:54,ads_walk:73,crouch_walk:136,still_stand:32,still_crouch:270,prone:187";
		case "sd_area_mp_bog_5_2": return "sprint:161,run:166,ads_walk:77,crouch_walk:179,still_stand:40,still_crouch:77,prone:25";
		case "sd_area_mp_bog_5_3": return "sprint:76,run:109,ads_walk:179,crouch_walk:230,still_stand:53,still_crouch:149,prone:25";
		case "sd_area_mp_bog_5_4": return "sprint:103,run:39,ads_walk:118,crouch_walk:142,still_stand:25,still_crouch:119,prone:390";
		case "sd_area_mp_bog_6_0": return "sprint:197,run:135,ads_walk:82,crouch_walk:125,still_stand:33,still_crouch:47,prone:110";
		case "sd_area_mp_bog_6_2": return "sprint:103,run:144,ads_walk:237,crouch_walk:75,still_stand:86,still_crouch:25,prone:38";
		case "sd_area_mp_bog_6_3": return "sprint:77,run:94,ads_walk:100,crouch_walk:130,still_stand:95,still_crouch:214,prone:25";
		case "sd_area_mp_bog_6_4": return "sprint:53,run:98,ads_walk:146,crouch_walk:79,still_stand:116,still_crouch:112,prone:101";
		case "sd_area_mp_bog_7_0": return "sprint:80,run:119,ads_walk:58,crouch_walk:106,still_stand:59,still_crouch:248,prone:77";
		case "sd_area_mp_bog_7_1": return "sprint:63,run:92,ads_walk:115,crouch_walk:85,still_stand:104,still_crouch:25,prone:285";
		case "sd_area_mp_bog_7_2": return "sprint:76,run:59,ads_walk:102,crouch_walk:170,still_stand:36,still_crouch:246,prone:188";
		case "sd_area_mp_bog_7_3": return "sprint:92,run:50,ads_walk:49,crouch_walk:211,still_stand:84,still_crouch:167,prone:150";
		case "sd_area_mp_bog_7_4": return "sprint:161,run:127,ads_walk:25,crouch_walk:106,still_stand:25,still_crouch:25,prone:400";
		case "sd_area_mp_bog_8_0": return "sprint:55,run:82,ads_walk:130,crouch_walk:147,still_stand:84,still_crouch:99,prone:214";
		case "sd_area_mp_bog_8_1": return "sprint:53,run:93,ads_walk:181,crouch_walk:173,still_stand:84,still_crouch:97,prone:116";
		case "sd_area_mp_bog_8_2": return "sprint:73,run:28,ads_walk:62,crouch_walk:184,still_stand:25,still_crouch:400,prone:79";
		case "sd_area_mp_bog_8_3": return "sprint:98,run:111,ads_walk:76,crouch_walk:29,still_stand:101,still_crouch:202,prone:27";
		case "sd_area_mp_bog_8_4": return "sprint:69,run:47,ads_walk:42,crouch_walk:73,still_stand:84,still_crouch:148,prone:355";
		case "sd_area_mp_bog_9_0": return "sprint:25,run:90,ads_walk:271,crouch_walk:64,still_stand:131,still_crouch:29,prone:118";
		case "sd_area_mp_bog_9_1": return "sprint:71,run:94,ads_walk:125,crouch_walk:136,still_stand:93,still_crouch:116,prone:119";
		case "sd_area_mp_bog_9_2": return "sprint:137,run:91,ads_walk:98,crouch_walk:53,still_stand:119,still_crouch:90,prone:37";
		case "sd_area_mp_bog_9_3": return "sprint:47,run:60,ads_walk:59,crouch_walk:276,still_stand:47,still_crouch:148,prone:296";
		case "sd_area_mp_bog_9_4": return "sprint:61,run:109,ads_walk:70,crouch_walk:149,still_stand:96,still_crouch:170,prone:74";
		case "sd_area_mp_bog_10_0": return "sprint:147,run:173,ads_walk:147,crouch_walk:79,still_stand:69,still_crouch:25,prone:25";
		case "sd_area_mp_bog_10_1": return "sprint:128,run:213,ads_walk:87,crouch_walk:76,still_stand:63,still_crouch:25,prone:74";
		case "sd_area_mp_bog_10_2": return "sprint:140,run:107,ads_walk:85,crouch_walk:95,still_stand:145,still_crouch:25,prone:25";
		case "sd_area_mp_bog_10_3": return "sprint:76,run:111,ads_walk:100,crouch_walk:76,still_stand:176,still_crouch:25,prone:25";
		case "sd_area_mp_bog_10_4": return "sprint:287,run:110,ads_walk:73,crouch_walk:94,still_stand:39,still_crouch:39,prone:25";
		case "sd_area_mp_bog_11_-1": return "sprint:25,run:25,ads_walk:25,crouch_walk:25,still_stand:306,still_crouch:89,prone:25";
		case "sd_area_mp_bog_11_0": return "sprint:102,run:124,ads_walk:113,crouch_walk:94,still_stand:112,still_crouch:92,prone:25";
		case "sd_area_mp_bog_11_1": return "sprint:175,run:170,ads_walk:84,crouch_walk:47,still_stand:81,still_crouch:33,prone:25";
		case "sd_area_mp_bog_11_2": return "sprint:134,run:94,ads_walk:104,crouch_walk:60,still_stand:110,still_crouch:123,prone:25";
		case "sd_area_mp_bog_11_3": return "sprint:238,run:63,ads_walk:25,crouch_walk:109,still_stand:25,still_crouch:288,prone:25";
		case "sd_area_mp_bog_12_1": return "sprint:49,run:129,ads_walk:224,crouch_walk:25,still_stand:151,still_crouch:28,prone:25";
		case "sd_area_mp_bog_12_2": return "sprint:185,run:76,ads_walk:47,crouch_walk:39,still_stand:136,still_crouch:32,prone:62";
		case "sd_area_mp_bog_12_3": return "sprint:188,run:61,ads_walk:25,crouch_walk:136,still_stand:31,still_crouch:301,prone:25";
		case "sd_area_mp_bog_12_4": return "sprint:25,run:25,ads_walk:25,crouch_walk:25,still_stand:25,still_crouch:25,prone:400";
		case "sd_area_mp_crossfire_6_-8": return "sprint:32,run:78,ads_walk:25,crouch_walk:31,still_stand:324,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_6_-6": return "sprint:25,run:41,ads_walk:54,crouch_walk:77,still_stand:253,still_crouch:169,prone:25";
		case "sd_area_mp_crossfire_7_-9": return "sprint:63,run:146,ads_walk:112,crouch_walk:45,still_stand:152,still_crouch:53,prone:25";
		case "sd_area_mp_crossfire_7_-8": return "sprint:88,run:104,ads_walk:76,crouch_walk:25,still_stand:185,still_crouch:46,prone:51";
		case "sd_area_mp_crossfire_7_-7": return "sprint:91,run:113,ads_walk:159,crouch_walk:146,still_stand:83,still_crouch:82,prone:25";
		case "sd_area_mp_crossfire_7_-6": return "sprint:190,run:185,ads_walk:65,crouch_walk:67,still_stand:25,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_7_-5": return "sprint:77,run:119,ads_walk:185,crouch_walk:112,still_stand:97,still_crouch:67,prone:29";
		case "sd_area_mp_crossfire_7_-2": return "sprint:399,run:34,ads_walk:25,crouch_walk:25,still_stand:25,still_crouch:38,prone:25";
		case "sd_area_mp_crossfire_7_-1": return "sprint:165,run:70,ads_walk:25,crouch_walk:25,still_stand:218,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_8_-9": return "sprint:72,run:75,ads_walk:78,crouch_walk:95,still_stand:113,still_crouch:242,prone:25";
		case "sd_area_mp_crossfire_8_-8": return "sprint:189,run:108,ads_walk:147,crouch_walk:87,still_stand:52,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_8_-7": return "sprint:43,run:135,ads_walk:164,crouch_walk:158,still_stand:108,still_crouch:38,prone:83";
		case "sd_area_mp_crossfire_8_-6": return "sprint:40,run:97,ads_walk:142,crouch_walk:139,still_stand:115,still_crouch:147,prone:54";
		case "sd_area_mp_crossfire_8_-5": return "sprint:62,run:102,ads_walk:111,crouch_walk:160,still_stand:67,still_crouch:171,prone:117";
		case "sd_area_mp_crossfire_8_-4": return "sprint:34,run:119,ads_walk:77,crouch_walk:183,still_stand:50,still_crouch:227,prone:132";
		case "sd_area_mp_crossfire_8_-3": return "sprint:135,run:234,ads_walk:25,crouch_walk:34,still_stand:60,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_8_-2": return "sprint:281,run:98,ads_walk:25,crouch_walk:25,still_stand:72,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_9_-9": return "sprint:114,run:94,ads_walk:119,crouch_walk:39,still_stand:164,still_crouch:25,prone:50";
		case "sd_area_mp_crossfire_9_-8": return "sprint:58,run:101,ads_walk:45,crouch_walk:127,still_stand:41,still_crouch:316,prone:102";
		case "sd_area_mp_crossfire_9_-7": return "sprint:107,run:114,ads_walk:110,crouch_walk:25,still_stand:181,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_9_-6": return "sprint:37,run:30,ads_walk:122,crouch_walk:150,still_stand:107,still_crouch:302,prone:71";
		case "sd_area_mp_crossfire_9_-5": return "sprint:65,run:61,ads_walk:142,crouch_walk:119,still_stand:76,still_crouch:205,prone:190";
		case "sd_area_mp_crossfire_9_-4": return "sprint:63,run:102,ads_walk:142,crouch_walk:128,still_stand:122,still_crouch:45,prone:163";
		case "sd_area_mp_crossfire_9_-3": return "sprint:132,run:201,ads_walk:41,crouch_walk:76,still_stand:60,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_9_-2": return "sprint:131,run:138,ads_walk:69,crouch_walk:51,still_stand:113,still_crouch:46,prone:25";
		case "sd_area_mp_crossfire_10_-9": return "sprint:319,run:85,ads_walk:25,crouch_walk:25,still_stand:25,still_crouch:25,prone:152";
		case "sd_area_mp_crossfire_10_-8": return "sprint:219,run:152,ads_walk:51,crouch_walk:25,still_stand:54,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_10_-7": return "sprint:64,run:66,ads_walk:161,crouch_walk:114,still_stand:85,still_crouch:96,prone:357";
		case "sd_area_mp_crossfire_10_-6": return "sprint:69,run:105,ads_walk:66,crouch_walk:151,still_stand:51,still_crouch:180,prone:224";
		case "sd_area_mp_crossfire_10_-5": return "sprint:82,run:65,ads_walk:96,crouch_walk:104,still_stand:136,still_crouch:125,prone:124";
		case "sd_area_mp_crossfire_10_-4": return "sprint:87,run:62,ads_walk:145,crouch_walk:139,still_stand:110,still_crouch:90,prone:161";
		case "sd_area_mp_crossfire_10_-3": return "sprint:108,run:87,ads_walk:98,crouch_walk:190,still_stand:82,still_crouch:97,prone:58";
		case "sd_area_mp_crossfire_10_-2": return "sprint:270,run:97,ads_walk:55,crouch_walk:63,still_stand:25,still_crouch:25,prone:134";
		case "sd_area_mp_crossfire_11_-9": return "sprint:237,run:48,ads_walk:25,crouch_walk:25,still_stand:169,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_11_-8": return "sprint:267,run:138,ads_walk:25,crouch_walk:25,still_stand:45,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_11_-7": return "sprint:25,run:129,ads_walk:111,crouch_walk:25,still_stand:259,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_11_-6": return "sprint:45,run:90,ads_walk:106,crouch_walk:178,still_stand:67,still_crouch:176,prone:215";
		case "sd_area_mp_crossfire_11_-5": return "sprint:58,run:61,ads_walk:83,crouch_walk:122,still_stand:77,still_crouch:260,prone:191";
		case "sd_area_mp_crossfire_11_-4": return "sprint:87,run:78,ads_walk:124,crouch_walk:117,still_stand:81,still_crouch:70,prone:343";
		case "sd_area_mp_crossfire_11_-3": return "sprint:118,run:27,ads_walk:66,crouch_walk:91,still_stand:232,still_crouch:29,prone:25";
		case "sd_area_mp_crossfire_11_-2": return "sprint:88,run:88,ads_walk:55,crouch_walk:125,still_stand:52,still_crouch:289,prone:25";
		case "sd_area_mp_crossfire_12_-9": return "sprint:30,run:49,ads_walk:25,crouch_walk:25,still_stand:371,still_crouch:25,prone:25";
		case "sd_area_mp_crossfire_12_-5": return "sprint:27,run:51,ads_walk:261,crouch_walk:185,still_stand:64,still_crouch:122,prone:320";
		case "sd_area_mp_crossfire_12_-4": return "sprint:81,run:61,ads_walk:308,crouch_walk:123,still_stand:58,still_crouch:87,prone:169";
		case "sd_area_mp_crossfire_12_-3": return "sprint:77,run:68,ads_walk:194,crouch_walk:149,still_stand:60,still_crouch:91,prone:294";
		case "sd_area_mp_crossfire_12_-2": return "sprint:127,run:128,ads_walk:37,crouch_walk:148,still_stand:68,still_crouch:111,prone:25";
		case "sd_phase_0": return "sprint:269,run:96,ads_walk:28,crouch_walk:25,still_stand:79,still_crouch:25,prone:25";
		case "sd_phase_1": return "sprint:125,run:148,ads_walk:64,crouch_walk:64,still_stand:89,still_crouch:61,prone:58";
		case "sd_phase_2": return "sprint:78,run:102,ads_walk:106,crouch_walk:112,still_stand:90,still_crouch:113,prone:155";
		case "sd_phase_3": return "sprint:46,run:72,ads_walk:138,crouch_walk:138,still_stand:113,still_crouch:143,prone:142";
		case "sd_phase_4": return "sprint:49,run:71,ads_walk:143,crouch_walk:134,still_stand:135,still_crouch:137,prone:59";
		case "sd_phase_5": return "sprint:63,run:66,ads_walk:144,crouch_walk:93,still_stand:135,still_crouch:144,prone:80";
		case "respawn_sprint_dwell": return "0.25,0.35,0.50,0.70,0.95,1.25,1.65,2.15,3.25";
		case "respawn_sprint_next": return "run:600,crouch_walk:244,ads_walk:117,still_stand:32,still_crouch:7";
		case "respawn_sprint_share": return "150";
		case "respawn_run_dwell": return "0.15,0.20,0.25,0.35,0.45,0.55,0.75,1.10,1.80";
		case "respawn_run_next": return "sprint:573,still_stand:229,ads_walk:95,crouch_walk:91,still_crouch:11,prone:1";
		case "respawn_run_share": return "110";
		case "respawn_ads_walk_dwell": return "0.15,0.20,0.25,0.30,0.40,0.50,0.70,1.00,1.65";
		case "respawn_ads_walk_next": return "still_stand:777,run:157,sprint:40,crouch_walk:17,still_crouch:8";
		case "respawn_ads_walk_share": return "63";
		case "respawn_crouch_walk_dwell": return "0.15,0.25,0.30,0.35,0.45,0.60,0.85,1.20,1.75";
		case "respawn_crouch_walk_next": return "still_crouch:796,sprint:83,run:56,prone:28,ads_walk:18,still_stand:18";
		case "respawn_crouch_walk_share": return "129";
		case "respawn_still_stand_dwell": return "0.20,0.25,0.30,0.45,0.60,0.85,1.15,1.70,2.55";
		case "respawn_still_stand_next": return "ads_walk:503,run:360,still_crouch:109,sprint:20,crouch_walk:9";
		case "respawn_still_stand_share": return "195";
		case "respawn_still_crouch_dwell": return "0.20,0.30,0.40,0.50,0.65,0.95,1.35,1.95,3.65";
		case "respawn_still_crouch_next": return "crouch_walk:831,still_stand:72,run:43,prone:36,sprint:17,ads_walk:1";
		case "respawn_still_crouch_share": return "297";
		case "respawn_prone_dwell": return "0.55,0.80,0.95,1.65,1.80,1.90,3.15,4.65,6.25";
		case "respawn_prone_next": return "still_crouch:607,crouch_walk:279,run:98,still_stand:16";
		case "respawn_prone_share": return "56";
	}
	
	return undefined;
}
