/*
	_bot_motor_data
	GENERATED by tools/gen_motor_model.py from human demo data. Do not edit.
	Human movement state machine per profile: dwell-time deciles (s),
	next-state weights (per mille) and time share (per mille).
	  sd: sprint 20%, run 22%, ads_walk 9%, crouch_walk 10%, still_stand 23%, still_crouch 11%, prone 6% (565 player-min)
	  respawn: sprint 15%, run 11%, ads_walk 6%, crouch_walk 13%, still_stand 19%, still_crouch 30%, prone 6% (118 player-min)
*/

/*
	Returns the data string for key (profile_state_field), or undefined.
*/
motor_data( key )
{
	switch ( key )
	{
		case "sd_sprint_dwell": return "0.20,0.30,0.40,0.55,0.70,0.95,1.20,1.70,2.80";
		case "sd_sprint_next": return "run:621,crouch_walk:252,ads_walk:103,still_stand:20,still_crouch:4";
		case "sd_sprint_share": return "201";
		case "sd_run_dwell": return "0.15,0.20,0.30,0.35,0.50,0.65,0.85,1.15,1.70";
		case "sd_run_next": return "sprint:542,still_stand:223,ads_walk:117,crouch_walk:106,still_crouch:12";
		case "sd_run_share": return "216";
		case "sd_ads_walk_dwell": return "0.15,0.20,0.25,0.35,0.40,0.55,0.70,0.95,1.40";
		case "sd_ads_walk_next": return "still_stand:698,run:210,crouch_walk:54,sprint:25,still_crouch:13,prone:1";
		case "sd_ads_walk_share": return "88";
		case "sd_crouch_walk_dwell": return "0.20,0.25,0.30,0.35,0.45,0.55,0.70,0.90,1.40";
		case "sd_crouch_walk_next": return "still_crouch:417,run:247,sprint:135,prone:94,ads_walk:79,still_stand:28";
		case "sd_crouch_walk_share": return "96";
		case "sd_still_stand_dwell": return "0.15,0.20,0.30,0.40,0.50,0.65,0.85,1.25,2.25";
		case "sd_still_stand_next": return "run:517,ads_walk:364,still_crouch:65,crouch_walk:26,sprint:26,prone:1";
		case "sd_still_stand_share": return "226";
		case "sd_still_crouch_dwell": return "0.20,0.20,0.30,0.40,0.50,0.70,1.00,1.55,2.65";
		case "sd_still_crouch_next": return "crouch_walk:633,still_stand:178,run:96,ads_walk:42,prone:35,sprint:16";
		case "sd_still_crouch_share": return "113";
		case "sd_prone_dwell": return "0.45,0.75,0.90,1.20,1.65,2.05,2.65,4.50,7.35";
		case "sd_prone_next": return "crouch_walk:425,still_crouch:385,run:172,still_stand:17,ads_walk:2";
		case "sd_prone_share": return "60";
		case "respawn_sprint_dwell": return "0.25,0.35,0.50,0.70,0.95,1.25,1.65,2.15,3.25";
		case "respawn_sprint_next": return "run:600,crouch_walk:244,ads_walk:117,still_stand:32,still_crouch:7";
		case "respawn_sprint_share": return "150";
		case "respawn_run_dwell": return "0.15,0.20,0.25,0.35,0.45,0.55,0.75,1.10,1.80";
		case "respawn_run_next": return "sprint:573,still_stand:229,ads_walk:95,crouch_walk:91,still_crouch:11,prone:1";
		case "respawn_run_share": return "110";
		case "respawn_ads_walk_dwell": return "0.15,0.20,0.25,0.30,0.40,0.50,0.70,1.00,1.65";
		case "respawn_ads_walk_next": return "still_stand:777,run:157,sprint:40,crouch_walk:17,still_crouch:8";
		case "respawn_ads_walk_share": return "63";
		case "respawn_crouch_walk_dwell": return "0.15,0.25,0.30,0.35,0.45,0.60,0.85,1.20,1.75";
		case "respawn_crouch_walk_next": return "still_crouch:796,sprint:83,run:56,prone:28,ads_walk:18,still_stand:18";
		case "respawn_crouch_walk_share": return "129";
		case "respawn_still_stand_dwell": return "0.20,0.25,0.30,0.45,0.60,0.85,1.15,1.70,2.55";
		case "respawn_still_stand_next": return "ads_walk:503,run:360,still_crouch:109,sprint:20,crouch_walk:9";
		case "respawn_still_stand_share": return "195";
		case "respawn_still_crouch_dwell": return "0.20,0.30,0.40,0.50,0.65,0.95,1.35,1.95,3.65";
		case "respawn_still_crouch_next": return "crouch_walk:831,still_stand:72,run:43,prone:36,sprint:17,ads_walk:1";
		case "respawn_still_crouch_share": return "297";
		case "respawn_prone_dwell": return "0.55,0.80,0.95,1.65,1.80,1.90,3.15,4.65,6.25";
		case "respawn_prone_next": return "still_crouch:607,crouch_walk:279,run:98,still_stand:16";
		case "respawn_prone_share": return "56";
	}
	
	return undefined;
}
