#!/usr/bin/env python3
"""
Learns grenade lineups from human demos and writes GSC data for the bots
(maps/mp/bots/_bot_nade_data.gsc): where real players threw grenades from,
where they landed, and when in the round, per map.

People throw at places enemies will be (chokepoints, spawn exits, sites), so
a bot near a throw spot can throw the same grenade with the same intent.

Throws: gravity-arc missiles (not claymores/C4 or tubes/rockets) lasting
0.5-6s. The first sample's trajectory base is the release point, the last one
the final bounce (about where it rests). The thrower is the nearest player to
the release point at that moment (the export has no owner); throws by bots or
with no player within 90u are skipped. S&D round time comes from round starts
(live-player count jumping by 6+ within 3s).

Usage: tools/gen_nade_model.py output/demos/demo0000 output/demos/demo0001 ...
"""
import bisect
import collections
import csv
import json
import math
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import demostats  # noqa: E402
import gen_map_model  # noqa: E402
import nadestats  # noqa: E402

OUT = "maps/mp/bots/_bot_nade_data.gsc"
CHUNK = 30


def main():
	lineups = collections.defaultdict(list)  # map -> [(throw, land, round_s)]
	for base in sys.argv[1:]:
		meta = json.load(open(base + ".meta.json"))
		names = {k: re.sub(r"\^.", "", v["name"]) for k, v in meta["names"].items()}
		bots = demostats.bot_clients(meta, names)
		wins = gen_map_model.map_windows(meta)
		snap = collections.defaultdict(list)
		for r in csv.DictReader(open(base + ".players.csv")):
			snap[int(r["t"])].append(r)
		times = sorted(snap)
		starts, _ = nadestats.round_starts(base)
		# per missile number: first and last sample of each flight
		flights = []
		for th in nadestats.throws_of_rows(base):
			flights.append(th)
		for th in flights:
			dur = (th["last"] - th["first"]) / 1000
			if th["tr"] in ("0", "2") or not 0.5 <= dur <= 6:
				continue
			w = gen_map_model.window_of(wins, th["first"])
			if not w:
				continue
			throw, land = th["p0"], th["p1"]
			if math.dist(throw[:2], land[:2]) < 150:
				continue  # dropped at the feet / cooked in hand
			i = bisect.bisect_left(times, th["first"])
			best = None
			for t in times[max(0, i - 2):i + 1]:
				for r in snap[t]:
					d = math.dist(throw, (float(r["x"]), float(r["y"]), float(r["z"]) + 50))
					if best is None or d < best[0]:
						best = (d, r)
			if not best or best[0] > 90 or best[1]["client"] in bots:
				continue
			rs = -1
			if w[2] == "sd":
				k = bisect.bisect_right(starts, th["first"]) - 1
				rs = int((th["first"] - starts[k]) / 1000) if k >= 0 else -1
			feet = (float(best[1]["x"]), float(best[1]["y"]), float(best[1]["z"]))
			lineups[w[1]].append((feet, land, rs))

	lines, summary = [], []
	for m, ls in sorted(lineups.items()):
		ents = [f"{t[0]:.0f} {t[1]:.0f} {t[2]:.0f} {l[0]:.0f} {l[1]:.0f} {l[2]:.0f} {rs}" for t, l, rs in ls]
		# GSC string literals are kept short: CHUNK lineups per part
		parts = [ents[i:i + CHUNK] for i in range(0, len(ents), CHUNK)]
		lines.append(f'\t\tcase "{m}_parts": return {len(parts)};')
		for i, part in enumerate(parts):
			lines.append(f'\t\tcase "{m}_{i}": return "{";".join(part)}";')
		early = sum(1 for _, _, rs in ls if 0 <= rs <= 30)
		summary.append(f"{m}: {len(ls)} human throws ({early} in the first 30s of a round)")

	src = [
		"/*",
		"\t_bot_nade_data",
		"\tGENERATED by tools/gen_nade_model.py from human demo data. Do not edit.",
		"\tPer map: <map>_parts = number of parts; <map>_<i> = up to 30 grenade",
		"\tlineups as \"tx ty tz lx ly lz round_s\" joined by ';'",
		"\t(thrower's feet, where it landed, seconds into the S&D round or -1).",
	] + [f"\t  {s}" for s in summary] + [
		"*/",
		"",
		"/*",
		"\tReturns the data for key, or undefined when the map has no data.",
		"*/",
		"nade_data( key )",
		"{",
		"\tswitch ( key )",
		"\t{",
	] + lines + [
		"\t}",
		"\t",
		"\treturn undefined;",
		"}",
		"",
	]
	with open(OUT, "wb") as f:
		f.write("\r\n".join(src).encode())
	print("\n".join(summary))
	print(f"wrote {OUT}")
	return 0


if __name__ == "__main__":
	sys.exit(main())
